backend:
  name: github
  repo: nawwab/myPortfolioWebsite

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Thumbnail Image", name: "thumbnail", widget: "image"}
      - {label: "Publish Date", name: "date", widget: "datetime", picker_utc: true}
      - {label: "Body", name: "body", widget: "markdown"}