backend:
  name: github
  repo: nawwab/myPortfolioWebsite

media_folder: "static/postimages/"
public_folder: "/postimages"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Thumbnail Image", name: "thumbnail", widget: "image"}
      - {label: "Publish Date", name: "date", widget: "datetime", picker_utc: true}
      - {label: "Body", name: "body", widget: "markdown"}